spring.application.name=AiTutorApplication

spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.api-key=sk-or-v1cdr-h47b53ac2564c618c35012ef9e7658f042a3ad47b866a83741fa2a618fd7f5bcb0
spring.ai.openai.model=openai/gpt-5-nano

spring.datasource.url=jdbc:postgresql://localhost:5432/tutor
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
